baseURL = "/"
languageCode = "de"
removePathAccents = true
preserveTaxonomyNames = true
disableFastRender = true
buildFuture = true

[permalinks]
posts = "/:filename/"
tags = "/tag/:slug/"

[taxonomies]
tag = "tags"