baseURL: https://www.marco-jakob.ch/
title: Marco Jakob
languageCode: de
removePathAccents: true
disableFastRender: true
preserveTaxonomyNames: true

Params:
  description: Lern-Blog von Marco Jakob
  email: info@marco-jakob.ch
  favicon: img/favicon.png
  primaryImage: img/default-img.jpg

permalinks:
  posts: /:filename/
  tags: /tag/:slug/

taxonomies:
  tag: tags
